"""VP solver for alternating substitutions sigma_a, sigma_b (phases a, b).

Phase-p tiles are subdivided by sigma_p into phase-q tiles (q = other).
Among phase-q tiles:  F-F- contacts (-2e_k, (D^p_k)^{-1}),  F+F- contacts (-2e_k, H^p_{u_k}),
sibling contacts from sigma_p.   Virtual pointers of phase-q tiles are H^q; the VP relation
across their axial faces must be D^q_j.
"""
import itertools, sys, pickle, time
from fast import *
from vpsolve import D_candidates
from vpsolve2 import canonical_pis
from vpsolve import involutions


class AltSolver:
    def __init__(self, E):
        self.E = E
        d = E.d
        self.d = d
        self.one = (1,) * d
        self.m1 = tuple(-1 for _ in range(d))
        self.zero = (0,) * d
        self.mixed = [w for w in itertools.product((1, -1), repeat=d) if w != self.one and w != self.m1]
        self.coset = {w: [gi for gi, g in enumerate(E.frames) if apply(g, self.one) == tuple(-x for x in w)]
                      for w in self.mixed}
        self.normal = []
        for f, (v, i, s) in enumerate(E.faces):
            n = [0] * d
            n[i] = s
            self.normal.append(tuple(n))
        self._sf = {}

    def shared(self, B):
        r = self._sf.get(B)
        if r is None:
            r = self.E.shared_faces(B)
            self._sf[B] = r
        return r

    def contacts(self, Hp, Dp):
        """contacts among children-phase tiles generated by parent phase (Hp, Dp)."""
        E = self.E
        d = self.d
        out = []
        for k in range(d):
            ek2 = tuple(-2 * (i == k) for i in range(d))
            out.append((ek2, E.inv[Dp[k]]))
            uk = tuple(1 - 2 * (i == k) for i in range(d))
            if uk in Hp:
                out.append((ek2, Hp[uk]))
        ws = [w for w in itertools.product((1, -1), repeat=d) if w != self.one]
        for u in ws:
            if u not in Hp:
                continue
            for i in range(d):
                u2 = list(u); u2[i] = -u2[i]; u2 = tuple(u2)
                if u2 == self.one or u2 not in Hp:
                    continue
                out.append(E.rel((u, Hp[u]), (u2, Hp[u2])))
        res = set()
        for B in out:
            res.add(B)
            res.add(E.rel(B, E.root))
        return res

    def propagate_one(self, Hq, Dq, contacts):
        E = self.E
        d = self.d
        changed = False
        for B in contacts:
            t, gb = B
            ginv = E.inv[gb]
            for f, fB, i in self.shared(B):
                v = E.faces[f][0]
                vB = E.faces[fB][0]
                if v not in Hq:
                    continue
                hw = Hq[v]
                img = apply(E.frames[E.inv[hw]], self.normal[f])
                j = next(k for k in range(d) if img[k] != 0)
                if img[j] != -1:
                    return None
                req = E.mul[E.mul[ginv][hw]][E.inv[Dq[j]]]
                if vB in Hq:
                    if Hq[vB] != req:
                        return None
                else:
                    if apply(E.frames[req], self.one) != tuple(-x for x in vB):
                        return None
                    Hq[vB] = req
                    changed = True
        return changed

    def propagate(self, H, D):
        while True:
            ch = False
            for p, q in (('a', 'b'), ('b', 'a')):
                cts = self.contacts(H[p], D[p])
                r = self.propagate_one(H[q], D[q], cts)
                if r is None:
                    return False
                ch = ch or r
            if not ch:
                return True

    def solve_for(self, D, sols, limit=None):
        E = self.E
        base = {self.zero: 0, self.m1: 0}
        H0 = {'a': dict(base), 'b': dict(base)}

        def rec(H):
            if limit and len(sols) >= limit:
                return
            H = {'a': dict(H['a']), 'b': dict(H['b'])}
            if not self.propagate(H, D):
                return
            free = [(p, w) for p in ('a', 'b') for w in self.mixed if w not in H[p]]
            if not free:
                sols.append(({p: {k: E.frames[x] for k, x in D[p].items()} for p in D},
                             {p: {w: E.frames[h] for w, h in H[p].items()} for p in H}))
                return
            p, w = free[0]
            for h in self.coset[w]:
                H2 = {'a': dict(H['a']), 'b': dict(H['b'])}
                H2[p][w] = h
                rec(H2)

        rec(H0)


def all_D(E, pi, selfinv_required=True):
    d = E.d
    reps = [k for k in range(d) if k <= pi[k]]
    cand = [D_candidates(E, k, pi[k]) for k in reps]
    for choice in itertools.product(*cand):
        D = {}
        ok = True
        for k, gi in zip(reps, choice):
            D[k] = gi
            if pi[k] != k:
                D[pi[k]] = E.inv[gi]
            elif E.inv[gi] != gi:
                ok = False
        if not ok:
            continue
        if any(D[k] not in D_candidates(E, k, pi[k]) for k in range(d)):
            continue
        yield D


def gen_group(E, frames):
    G = {0}; gens = [E.fidx[f] for f in frames]; fr = [0]
    while fr:
        x = fr.pop()
        for g in gens:
            y = E.mul[x][g]
            if y not in G:
                G.add(y); fr.append(y)
    return len(G)


if __name__ == "__main__":
    d = int(sys.argv[1])
    E = Engine(d)
    S = AltSolver(E)
    t0 = time.time()
    sols = []
    Dlists = {}
    for pi in involutions(d):
        Dlists[tuple(sorted(pi.items()))] = list(all_D(E, pi))
    alld = [D for L in Dlists.values() for D in L]
    print("total D choices", len(alld), flush=True)
    # phase a: canonical pis only (global conjugation symmetry); phase b: all
    canon = [tuple(sorted(p.items())) for p in canonical_pis(d)]
    Da_list = [D for key in canon for D in Dlists[key]]
    n = 0
    for Da in Da_list:
        for Db in alld:
            s0 = len(sols)
            S.solve_for({'a': Da, 'b': Db}, sols)
            n += 1
        print("Da done", n, "sols", len(sols), round(time.time() - t0, 1), flush=True)
    nonfrozen = []
    for Dd, H in sols:
        ga = gen_group(E, list(H['a'].values()) + list(H['b'].values()))
        nonfrozen.append((ga, Dd, H))
    from collections import Counter
    print(Counter(x[0] for x in nonfrozen))
    pickle.dump(nonfrozen, open('vpalt%d.pkl' % d, 'wb'))
